title: Shakespeare Programming Language
description: >
  A programming language that looks like Shakespeare's plays.
email: zmbc@uw.edu
github_username: zmbc

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal